# plato-tour-guide/tile.py
"""Tile data structure for the PLATO tour guide room."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class Tile:
    """
    A Tile is the atomic unit of knowledge in a PLATO room.
    
    Analogous to a museum label: it answers a specific question
    with a specific answer. Tiles have confidence scores that
    reflect how the answer was derived.
    
    Attributes:
        id: Unique identifier (hash of question+answer or UUID)
        question: The question this tile answers
        answer: The answer
        confidence: 0.0-1.0
            1.0 = verified by human (direct tile)
            0.9 = high-confidence direct match
            0.7 = consensus-snap (inferred, not verified)
            0.6 = partial snap
        tags: Keyword tags for matching/scoping
        source: Where this tile came from
            "human" = hand-written
            "orientation" = pre-programmed orientation tile
            "swarm" = generated by agent swarm
            "consensus_snap" = generated by consensus snap
            "cross_room" = fetched from neighbor room
        timestamp: When this tile was created
        swarm_flag: True if generated by swarm (Level 3/4)
        partials_count: Number of partials if swarm-generated
        spread: Semantic spread if consensus-snap
        notes: Uncertainty notes, snap type, etc.
    """
    question: str
    answer: str
    confidence: float
    id: Optional[str] = None
    tags: list[str] = field(default_factory=list)
    source: str = "human"
    timestamp: datetime = field(default_factory=datetime.now)
    swarm_flag: bool = False
    partials_count: int = 0
    spread: float = 0.0
    notes: str = ""

    def __post_init__(self):
        if self.id is None:
            import hashlib
            self.id = hashlib.sha256(
                f"{self.question}|{self.answer}".encode()
            ).hexdigest()[:16]

    def to_dict(self) -> dict:
        """Serialize for PLATO HTTP API submission."""
        return {
            "domain": "tour-guide",
            "question": self.question,
            "answer": self.answer,
            "confidence": self.confidence,
            "tags": self.tags,
            "source": self.source,
            "swarm_flag": self.swarm_flag,
            "partials_count": self.partials_count,
            "spread": self.spread,
            "notes": self.notes,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "Tile":
        """Deserialize from PLATO HTTP API response."""
        return cls(
            id=d.get("tile_id", d.get("id")),
            question=d["question"],
            answer=d.get("answer", d.get("content", "")),
            confidence=d.get("confidence", 0.5),
            tags=d.get("tags", []),
            source=d.get("source", "unknown"),
            swarm_flag=d.get("swarm_flag", False),
            partials_count=d.get("partials_count", 0),
            spread=d.get("spread", 0.0),
            notes=d.get("notes", ""),
        )

    def is_orientation(self) -> bool:
        """Check if this is a pre-programmed orientation tile."""
        return self.source == "orientation"

    def is_verified(self) -> bool:
        """Check if this tile has full confidence (human-verified)."""
        return self.confidence >= 1.0

    def is_consensus(self) -> bool:
        """Check if this tile was generated by consensus snap."""
        return self.swarm_flag and self.confidence < 1.0


@dataclass
class PartialAnswer:
    """
    A partial answer from a swarm agent.
    
    When the tour guide spawns agents to multiple rooms, each
    agent returns a PartialAnswer with their room, answer,
    confidence, and reasoning.
    """
    room: str
    answer: str
    confidence: float
    reasoning: str
    distance: float = 0.0  # Semantic distance from consensus (computed later)

    def to_dict(self) -> dict:
        return {
            "room": self.room,
            "answer": self.answer,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "distance": self.distance,
        }


@dataclass
class EscalationContext:
    """
    Tracks the state of a question as it moves through the cascade.
    
    This is the "tour guide's notebook" — it records what happened
    at each level so the interaction can be filed and the room can
    learn from it.
    """
    question: str
    user_mode: str = "unknown"  # "morning" | "afternoon" | "unknown"
    originating_room: str = ""
    cascade_level: int = 0  # 0-5
    partials: list[PartialAnswer] = field(default_factory=list)
    tiles_checked: list[str] = field(default_factory=list)
    timestamp: datetime = field(default_factory=datetime.now)
    answer: str = ""
    confidence: float = 0.0

    def to_dict(self) -> dict:
        return {
            "question": self.question,
            "user_mode": self.user_mode,
            "originating_room": self.originating_room,
            "cascade_level": self.cascade_level,
            "partials": [p.to_dict() for p in self.partials],
            "tiles_checked": self.tiles_checked,
            "answer": self.answer,
            "confidence": self.confidence,
            "timestamp": self.timestamp.isoformat(),
        }